import type { ProductInput } from "@/lib/ai/rankRecommendations";

// Comprehensive mock product catalogue
// Shape mirrors what the Kapruka MCP will return later
export const MOCK_PRODUCTS: ProductInput[] = [
  // Flowers
  {
    id: "fl-001",
    name: "Classic Red Rose Bouquet (12 stems)",
    price: 3500,
    category: "flowers",
    tags: ["roses", "romantic", "birthday", "anniversary", "mother", "partner"],
    rating: 4.8,
    reviewCount: 342,
    availableToday: true,
    availableTomorrow: true,
    description: "Fresh red roses wrapped in premium paper with a handwritten card.",
  },
  {
    id: "fl-002",
    name: "Mixed Seasonal Flower Arrangement",
    price: 2800,
    category: "flowers",
    tags: ["mixed flowers", "colorful", "birthday", "thank you", "mother", "friend"],
    rating: 4.6,
    reviewCount: 218,
    availableToday: true,
    availableTomorrow: true,
    description: "A vibrant mix of seasonal blooms arranged beautifully.",
  },
  {
    id: "fl-003",
    name: "Orchid Plant in Ceramic Pot",
    price: 6500,
    category: "flowers",
    tags: ["orchid", "plant", "elegant", "housewarming", "mother", "teacher"],
    rating: 4.9,
    reviewCount: 156,
    availableToday: false,
    availableTomorrow: true,
    description: "A long-lasting orchid plant in a beautiful ceramic pot.",
  },
  // Cakes
  {
    id: "ck-001",
    name: "Classic Chocolate Birthday Cake (1kg)",
    price: 4200,
    category: "cakes",
    tags: ["chocolate", "birthday", "celebration", "classic"],
    rating: 4.7,
    reviewCount: 489,
    availableToday: true,
    availableTomorrow: true,
    description: "Rich chocolate sponge with chocolate ganache frosting.",
  },
  {
    id: "ck-002",
    name: "Strawberry Cream Cake (1kg)",
    price: 3800,
    category: "cakes",
    tags: ["strawberry", "cream", "birthday", "anniversary", "partner"],
    rating: 4.5,
    reviewCount: 267,
    availableToday: true,
    availableTomorrow: true,
    description: "Light vanilla sponge with fresh strawberries and whipped cream.",
  },
  {
    id: "ck-003",
    name: "Premium Black Forest Cake (2kg)",
    price: 7500,
    category: "cakes",
    tags: ["black forest", "premium", "anniversary", "birthday", "celebration"],
    rating: 4.9,
    reviewCount: 312,
    availableToday: false,
    availableTomorrow: true,
    description: "Layers of chocolate sponge, cherries, and whipped cream.",
  },
  // Gift Hampers
  {
    id: "gh-001",
    name: "Dilmah Premium Tea Gift Set",
    price: 4500,
    category: "gifts",
    tags: ["tea", "hamper", "mother", "teacher", "colleague", "birthday", "thank you", "wellness"],
    rating: 4.8,
    reviewCount: 521,
    availableToday: false,
    availableTomorrow: true,
    description: "Assortment of 6 premium Dilmah tea varieties in an elegant gift box.",
  },
  {
    id: "gh-002",
    name: "Luxury Spa & Wellness Hamper",
    price: 8900,
    category: "gifts",
    tags: ["spa", "wellness", "self-care", "mother", "partner", "friend", "birthday", "anniversary"],
    rating: 4.7,
    reviewCount: 183,
    availableToday: false,
    availableTomorrow: true,
    description: "Bath salts, essential oils, candles, and premium skincare in a wicker basket.",
  },
  {
    id: "gh-003",
    name: "Gourmet Chocolate & Candy Hamper",
    price: 3200,
    category: "gifts",
    tags: ["chocolate", "sweets", "hamper", "child", "friend", "birthday", "celebration"],
    rating: 4.6,
    reviewCount: 298,
    availableToday: true,
    availableTomorrow: true,
    description: "Premium imported chocolates and artisan sweets in a beautiful box.",
  },
  {
    id: "gh-004",
    name: "Sri Lankan Spice & Food Hamper",
    price: 5800,
    category: "gifts",
    tags: ["food", "spices", "local", "housewarming", "colleague", "client", "unique"],
    rating: 4.9,
    reviewCount: 147,
    availableToday: false,
    availableTomorrow: true,
    description: "Authentic Ceylon spices, jams, and artisan local products.",
  },
  {
    id: "gh-005",
    name: "Premium Wine & Cheese Hamper",
    price: 14500,
    category: "gifts",
    tags: ["wine", "cheese", "premium", "anniversary", "partner", "client", "luxury"],
    rating: 4.8,
    reviewCount: 94,
    availableToday: false,
    availableTomorrow: true,
    description: "Selected wines paired with aged cheeses and gourmet crackers.",
  },
  // Electronics
  {
    id: "el-001",
    name: "JBL Clip 4 Bluetooth Speaker",
    price: 8900,
    category: "electronics",
    tags: ["speaker", "bluetooth", "portable", "gift", "music lover", "friend", "child"],
    rating: 4.7,
    reviewCount: 634,
    availableToday: false,
    availableTomorrow: true,
    description: "Compact waterproof Bluetooth speaker with carabiner clip.",
  },
  {
    id: "el-002",
    name: "Apple AirPods (3rd Gen)",
    price: 32000,
    category: "electronics",
    tags: ["airpods", "earphones", "apple", "premium", "music lover", "tech lover", "birthday"],
    rating: 4.9,
    reviewCount: 412,
    availableToday: false,
    availableTomorrow: true,
    description: "Spatial audio, adaptive EQ, and all-day battery life.",
  },
  {
    id: "el-003",
    name: "Xiaomi Smart Watch SE",
    price: 12000,
    category: "electronics",
    tags: ["smartwatch", "fitness", "tech", "health", "birthday", "graduation"],
    rating: 4.5,
    reviewCount: 287,
    availableToday: false,
    availableTomorrow: true,
    description: "AMOLED display, GPS, heart rate monitor, 14-day battery.",
  },
  // Fashion & Lifestyle
  {
    id: "fa-001",
    name: "Premium Cotton Saree (Handloom)",
    price: 9500,
    category: "fashion",
    tags: ["saree", "traditional", "mother", "grandmother", "festival", "birthday", "elegant"],
    rating: 4.8,
    reviewCount: 203,
    availableToday: false,
    availableTomorrow: true,
    description: "Hand-woven cotton saree with traditional border design.",
  },
  {
    id: "fa-002",
    name: "Leather Wallet — Men's Premium",
    price: 5500,
    category: "fashion",
    tags: ["wallet", "leather", "men", "father", "colleague", "birthday", "practical"],
    rating: 4.6,
    reviewCount: 178,
    availableToday: false,
    availableTomorrow: true,
    description: "Full-grain leather bifold wallet with RFID protection.",
  },
  // Books & Stationery
  {
    id: "bk-001",
    name: "Premium Leather Journal Set",
    price: 3800,
    category: "books",
    tags: ["journal", "stationery", "creative", "writer", "student", "graduation", "birthday"],
    rating: 4.7,
    reviewCount: 156,
    availableToday: false,
    availableTomorrow: true,
    description: "Handcrafted leather journal with pen set in a gift box.",
  },
  // Beauty & Care
  {
    id: "be-001",
    name: "Aromatherapy Candle Gift Set",
    price: 4200,
    category: "beauty",
    tags: ["candle", "aromatherapy", "relaxation", "mother", "partner", "friend", "wellness"],
    rating: 4.8,
    reviewCount: 234,
    availableToday: false,
    availableTomorrow: true,
    description: "Set of 3 premium soy wax candles in calming scents.",
  },
  {
    id: "be-002",
    name: "Luxury Skincare Gift Box",
    price: 11500,
    category: "beauty",
    tags: ["skincare", "luxury", "self-care", "mother", "partner", "birthday", "anniversary"],
    rating: 4.7,
    reviewCount: 167,
    availableToday: false,
    availableTomorrow: true,
    description: "Premium moisturiser, serum, and eye cream gift set.",
  },
];
